apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshot-controller
rules:
  - apiGroups:
      - snapshot.kaidotio.github.io
    resources:
      - snapshots
      - scheduledsnapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - snapshot.kaidotio.github.io
    resources:
      - snapshots/status
      - scheduledsnapshots/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - patch
