apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: snapshot-controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
      app.kubernetes.io/component: ""
