apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshot-controller
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - snapshot-controller
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
