apiVersion: v1
kind: Service
metadata:
  name: snapshot-controller
spec:
  selector:
    app.kubernetes.io/name: snapshot-controller
    app.kubernetes.io/component: ""
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: server
