name: snapshot-controller
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    env:
      IMAGE: snapshot-controller
      KUSTOMIZATION: manifests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/docker-build
          key: ${{ runner.os }}-snapshot-controller-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-snapshot-controller-docker-
      - uses: ./.github/actions/setup-docker
      - run: |
          IMAGE_PATH=${GITHUB_REPOSITORY}/${IMAGE}
          GHCR_IMAGE=ghcr.io/${IMAGE_PATH}
          TAG=${GITHUB_REF##*/}
          opt=""
          if [ -d /home/runner/.cache/docker-build ]; then
            opt="--cache-from type=local,src=/home/runner/.cache/docker-build"
          else
            opt="--cache-from type=registry,ref=$GHCR_IMAGE:main"
          fi
          (
            docker buildx build --target snapshot-capture --output type=docker,name=$GHCR_IMAGE/snapshot-capture:$TAG,push=true ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
          
            docker buildx build --target snapshot-diff --output type=docker,name=$GHCR_IMAGE/snapshot-diff:$TAG,push=true ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
          
            docker buildx build --target snapshot-worker --output type=docker,name=$GHCR_IMAGE/snapshot-worker:$TAG,push=true ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .

            docker buildx build --output type=docker,name=$GHCR_IMAGE:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
          )
          DIGEST=$(docker push $GHCR_IMAGE:$TAG | grep -Eo "sha256:[a-f0-9]{64}")

          if [ -n "$KUSTOMIZATION" ]; then
            git config --global user.email "kaidotio@gmail.com"
            git config --global user.name "kaidotio"
            branch=${IMAGE}
            git checkout -b ${branch}

            IFS_BAK=$IFS
            IFS=,
            targets=($KUSTOMIZATION)
            IFS=$IFS_BAK
            for target in "${targets[@]}"; do
              (
                cd ${target}
                kustomize edit set image ${GHCR_IMAGE}=${GHCR_IMAGE}@${DIGEST}
              )
            done

            git add ${targets[*]}
            if git commit -m "Deploy ${IMAGE}"; then
              git fetch origin ${{ github.ref_name }}
              git rebase origin/${{ github.ref_name }}
              git push -f origin ${branch}
              if [ $(gh pr list --head ${branch} --json id | jq '. | length') -eq 0 ]; then
                gh pr create --title "Update ${IMAGE}" --body "${GHCR_IMAGE}@${DIGEST}" --head ${branch}
              fi
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
