name: snapshot-controller
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  packages: write
  pull-requests: write
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /home/runner/.cache/docker-build
          key: ${{ runner.os }}-snapshot-controller-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-snapshot-controller-docker-
      - uses: ./.github/actions/setup-docker
      - run: |
          IMAGE_PATH=${GITHUB_REPOSITORY}
          GHCR_IMAGE=ghcr.io/${IMAGE_PATH}
          TAG=${GITHUB_REF##*/}
          opt=""
          if [ -d /home/runner/.cache/docker-build ]; then
            opt="--cache-from type=local,src=/home/runner/.cache/docker-build"
          else
            opt="--cache-from type=registry,ref=$GHCR_IMAGE:main"
          fi
          (
            docker buildx build --target snapshot-capture --output type=docker,name=$GHCR_IMAGE/snapshot-capture:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
            docker push $GHCR_IMAGE/snapshot-capture:$TAG
          
            docker buildx build --target snapshot-diff --output type=docker,name=$GHCR_IMAGE/snapshot-diff:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
            docker push $GHCR_IMAGE/snapshot-diff:$TAG
          
            docker buildx build --target snapshot-worker --output type=docker,name=$GHCR_IMAGE/snapshot-worker:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
            docker push $GHCR_IMAGE/snapshot-worker:$TAG

            docker buildx build --target snapshot-diff-server --output type=docker,name=$GHCR_IMAGE/snapshot-diff-server:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
            docker push $GHCR_IMAGE/snapshot-diff-server:$TAG

            docker buildx build --output type=docker,name=$GHCR_IMAGE:$TAG,push=false ${opt} --cache-to type=local,mode=max,dest=/home/runner/.cache/docker-build .
            docker push $GHCR_IMAGE:$TAG
          )
        env:
          GITHUB_TOKEN: ${{ github.token }}
